# Generated by Django 4.2.2 on 2023-08-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbposts',
            old_name='c',
            new_name='category',
        ),
    ]
