# Generated by Django 4.2.2 on 2023-08-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbquestions',
            name='post_user_id',
        ),
        migrations.RemoveField(
            model_name='dbreplies',
            name='question_user_id',
        ),
        migrations.AlterField(
            model_name='dbposts',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dbquestions',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dbreplies',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
